name: 小米自动刷步数

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || !github.event.sender.id || github.actor == 'BlueSkyClouds'
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Run 小米自动刷步数
        run: python3 function/xiaomi_sports/xiaomi.py
        env:
          Xiaomi_User: ${{ secrets.Xiaomi_User }}
          Xiaomi_Pw: ${{ secrets.Xiaomi_Pw }}
          Xiaomi_Bs: ${{ secrets.Xiaomi_Bs }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          QYWX_AM: ${{ secrets.QYWX_AM}}